// Data
export const ADD_DATASET_REQUEST = 'ADD_DATASET_REQUEST'
export const ADD_DATASET_SUCCESS = 'ADD_DATASET_SUCCESS'
export const ADD_DATASET_FAIL = 'ADD_DATASET_FAIL'

// Projects
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL'
