// Media
export const ADD_MEDIA_REQUEST = 'ADD_MEDIA_REQUEST'
export const ADD_MEDIA_SUCCESS = 'ADD_MEDIA_SUCCESS'
export const ADD_MEDIA_FAIL = 'ADD_MEDIA_FAIL'
export const GET_MEDIA_LIST_REQUEST = 'GET_MEDIA_LIST_REQUEST'
export const GET_MEDIA_LIST_SUCCESS = 'GET_MEDIA_LIST_SUCCESS'
export const GET_MEDIA_LIST_FAIL = 'GET_MEDIA_LIST_FAIL'

// Projects
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL'

// Label
export const ADD_TAG_LIST_REQUEST = 'ADD_TAG_LIST_REQUEST'
export const ADD_TAG_LIST_SUCCESS = 'ADD_TAG_LIST_SUCCESS'
export const ADD_TAG_LIST_FAIL = 'ADD_TAG_LIST_FAIL'
export const SET_TAG_VISIBILITY = 'SET_TAG_VISIBILITY'
export const UPDATE_LABEL_CONTENT = 'UPDATE_LABEL_CONTENT'
