// Data
export const ADD_DATASET_REQUEST = 'ADD_DATASET_REQUEST'
export const ADD_DATASET_SUCCESS = 'ADD_DATASET_SUCCESS'
export const ADD_DATASET_FAIL = 'ADD_DATASET_FAIL'

// Projects
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL'

// Label
export const ADD_TAG_LIST_REQUEST = 'ADD_TAG_LIST_REQUEST'
export const ADD_TAG_LIST_SUCCESS = 'ADD_TAG_LIST_SUCCESS'
export const ADD_TAG_LIST_FAIL = 'ADD_TAG_LIST_FAIL'
